version: '3.8'
services:
  dynamodb:
    container_name: "localstack_dynamodb_java"
    build: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
  cache_server:
    build:
      context: .
      args:
        - USERNAME=cache
    container_name: cache-server-java
    ports:
      - "8888:8888"
    environment:
      - DYNAMODB_HOST=dynamodb
      - DYNAMODB_PORT=4566
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8888
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_KEY=dummy
      - VT_API_KEY=${VT_API_KEY}
    depends_on:
      - dynamodb
    links:
      - dynamodb
