version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  cache_server:
    build:
      context: .
      args:
        - USERNAME=cache
    container_name: cache-server
    ports:
      - "8888:8888"
    environment:
      - DYNAMODB_HOST=dynamodb
      - DYNAMODB_PORT=8000
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8888
      - AWS_PROFILE=localstack
      - VT_API_KEY=${VT_API_KEY}
    volumes:
      - "~/.aws:/home/cache/.aws"
    depends_on:
      - dynamodb
    links:
      - dynamodb
